[{"TimeUTC":"2025-10-14 18:39:28","timestampInMs":1760467168427,"requestPath":"planning-git-main-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"djfk5-1760467167213-89fde9cd605f","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-git-main-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-git-main-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J0AA9PYAGY56B545FJ2MTS","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:27","timestampInMs":1760467167542,"requestPath":"planning-git-main-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"djfk5-1760467167213-89fde9cd605f","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-git-main-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-git-main-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":870,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J0AA9PYAGY56B545FJ2MTS","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:25","timestampInMs":1760467165360,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"7s9n5-1760467164425-fdbe18b75874","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J0A79VHM3WZRCMPPCRSVGM","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:24","timestampInMs":1760467164475,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"7s9n5-1760467164425-fdbe18b75874","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":868,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J0A79VHM3WZRCMPPCRSVGM","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:22","timestampInMs":1760467162314,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"q9d8v-1760467161319-4852b4c8d8f6","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"ERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J0A48NV86ZP8AGNS74J7JG","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:21","timestampInMs":1760467161365,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"q9d8v-1760467161319-4852b4c8d8f6","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":931,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J0A48NV86ZP8AGNS74J7JG","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:20","timestampInMs":1760467160211,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"74km5-1760467159216-8834854aaa1b","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J0A27BYR3GDZQ8R2G1HRCZ","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:19","timestampInMs":1760467159275,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"74km5-1760467159216-8834854aaa1b","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":916,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J0A27BYR3GDZQ8R2G1HRCZ","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:19","timestampInMs":1760467159176,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"5z26f-1760467158234-6b39ada07456","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J0A182VTGPK4ZVCBV0KH9Y","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:18","timestampInMs":1760467158274,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"5z26f-1760467158234-6b39ada07456","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":885,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J0A182VTGPK4ZVCBV0KH9Y","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:16","timestampInMs":1760467156138,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"pgfmf-1760467155203-c59b3ebb18c6","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"ERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09Y9CGCPFV4CEKCN954WY","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:15","timestampInMs":1760467155244,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"pgfmf-1760467155203-c59b3ebb18c6","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":878,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09Y9CGCPFV4CEKCN954WY","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:14","timestampInMs":1760467154064,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"f4hmb-1760467153131-d2937db230ca","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"ERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09W8VBRJ2FP080ND51E6Q","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:13","timestampInMs":1760467153179,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"f4hmb-1760467153131-d2937db230ca","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":869,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09W8VBRJ2FP080ND51E6Q","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:12","timestampInMs":1760467152992,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"gx47m-1760467152087-e0a3661a589c","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09V7Y8EFQM00GNN1TD6W8","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:12","timestampInMs":1760467152347,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"wrmw5-1760467151409-e51f5c4d7fe8","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"ERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09TK5QFPWFA81DE69KDWJ","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:12","timestampInMs":1760467152126,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"gx47m-1760467152087-e0a3661a589c","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":848,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09V7Y8EFQM00GNN1TD6W8","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:11","timestampInMs":1760467151461,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"wrmw5-1760467151409-e51f5c4d7fe8","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":871,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09TK5QFPWFA81DE69KDWJ","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:11","timestampInMs":1760467151458,"requestPath":"planning-git-main-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"rnkn9-1760467149932-668f804d6923","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-git-main-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-git-main-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09SPYNRDWH4ZBQ97103VT","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:11","timestampInMs":1760467151343,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"jmmp2-1760467150261-662e0ea2a5f5","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"ERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09SEYWDVB7EN5A8GFXE8H","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:11","timestampInMs":1760467151022,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"f4hmb-1760467150097-4a7587e3e838","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09S9SPB204Z05E17YV27K","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:10","timestampInMs":1760467150967,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"bvq4d-1760467149120-48cfdcab177c","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"ERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09REZQ86RN802VTMPWADG","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:10","timestampInMs":1760467150558,"requestPath":"planning-git-main-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"rnkn9-1760467149932-668f804d6923","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-git-main-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-git-main-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":879,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09SPYNRDWH4ZBQ97103VT","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:10","timestampInMs":1760467150302,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"jmmp2-1760467150261-662e0ea2a5f5","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":1020,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09SEYWDVB7EN5A8GFXE8H","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:10","timestampInMs":1760467150168,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"7fjlh-1760467149050-baed13a0aac1","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"ERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09RCK0CD3FMX40P6P1EJR","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:10","timestampInMs":1760467150137,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"f4hmb-1760467150097-4a7587e3e838","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":871,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09S9SPB204Z05E17YV27K","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:10","timestampInMs":1760467150094,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"nh45f-1760467147932-322ea3aa2026","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09Q9DY5H22KNMGAJ8FBFK","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:10","timestampInMs":1760467150030,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"8ftzj-1760467149095-f4991f47673f","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09RAEKFSDMAWDQZZ09Y77","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:09","timestampInMs":1760467149279,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"bvq4d-1760467149120-48cfdcab177c","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":737,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09REZQ86RN802VTMPWADG","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:09","timestampInMs":1760467149203,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"7fjlh-1760467149050-baed13a0aac1","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":901,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09RCK0CD3FMX40P6P1EJR","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:09","timestampInMs":1760467149134,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"8ftzj-1760467149095-f4991f47673f","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":872,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09RAEKFSDMAWDQZZ09Y77","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:08","timestampInMs":1760467148986,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"rjrl7-1760467147830-0c539ca661ab","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 38, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 1, in <module>\nfrom main import app\nFile \"/var/task/main.py\", line 41, in <module>\ninit_db()\nFile \"/var/task/modules/auth_manager.py\", line 40, in init_db\nos.chmod(DATABASE_PATH, 0o666)\nERROR initializing database: [Errno 30] Read-only file system: 'data/users.db'\nOSError: [Errno 30] Read-only file system: 'data/users.db'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09Q9E11K3YBVTWVZ4TN88","instanceId":"","concurrency":-1},{"TimeUTC":"2025-10-14 18:39:08","timestampInMs":1760467148078,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"rjrl7-1760467147830-0c539ca661ab","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":862,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09Q9E11K3YBVTWVZ4TN88","instanceId":"","concurrency":1},{"TimeUTC":"2025-10-14 18:39:08","timestampInMs":1760467148076,"requestPath":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"nh45f-1760467147932-322ea3aa2026","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"","type":"lambda","function":"/api/index.py","host":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentDomain":"planning-pbsax3se6-ronodeeps-projects-b30492f2.vercel.app","deploymentId":"dpl_5bxLZJeuRF8w7Kzxxo94PepgCJtp","durationMs":907,"region":"iad1","maxMemoryUsed":79,"memorySize":2048,"message":"","projectId":"prj_tgNz97PoikBUXw4uIlPwKGJoX3Fo","traceId":"","sessionId":"","invocationId":"01K7J09Q9DY5H22KNMGAJ8FBFK","instanceId":"","concurrency":1}]